### ISSUE TITLE
Bug: iterator returned by `MidiMessage::bytes()` does not iterate

### ISSUE THREAD

**Issue by Janonard** [wmedrano/wmidi#6]
I want to read the byte-representation of a message byte-per-byte. This should usually be possible by calling `MidiMessage::bytes`, which is method provided by the `Read` trait. However, the returned iterator always yields the first byte of the message.

#### `Cargo.toml`

``` toml
[package]
name = "wmidi-bug"
version = "0.1.0"
authors = ["Jan-Oliver Janonard opdenhoevel <jan.opdenhoevel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmidi = "3.0.1"
```

#### `main.rs`

``` rust
extern crate wmidi;

use std::convert::TryFrom;
use std::io::Read;
use wmidi::*;

fn main() {
    let message = MidiMessage::NoteOn(Channel::Ch1, Note::C0, Velocity::try_from(127).unwrap());
    for read_val in message.bytes() {
        if let Ok(byte) = read_val {
            println!("{}", byte);
        } else {
            panic!("Read error!");
        }
    }
}
```

#### Output

```
144
144
144
... (infinite loop)
```

#### Expected Output

```
144
24
127
